name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies in /steam-api/api
        run: |
          cd /steam-api/api
          npm install
        working-directory: ./steam-api/api

      - name: Install npm dependencies in /steam-api/frontend
        run: |
          cd /steam-api/frontend
          npm install
        working-directory: ./steam-api/frontend

      - name: Build the frontend
        run: |
          cd /steam-api/frontend
          npm run build
        working-directory: ./steam-api/frontend

      - name: Restart PM2
        run: |
          pm2 restart all
        working-directory: ./steam-api

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."  # Source directory to deploy from
          target: "/root/steam-api"  # Target directory on your VPS