name: Deploy to VPS

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build React Frontend
      working-directory: /steam-api/frontend
      run: |
        npm install
        npm run build

    - name: Prepare Express API
      working-directory: /steam-api/api
      run: |
        npm install

    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "./"  # Adjust this to the paths you want to copy, like "./frontend/build"
        target: "/"  # Target path on your VPS

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          cd /root/steam-api/api
          # Commands to restart your server, like:
          pm2 restart all
