name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
- name: Install npm dependencies in /steam-api/api
  run: |
    cd /root/steam-api/api
    npm install
  working-directory: /root/steam-api/api

- name: Install npm dependencies in /steam-api/frontend
  run: |
    cd /root/steam-api/frontend
    npm install
  working-directory: /root/steam-api/frontend

- name: Build the frontend
  run: |
    cd /root/steam-api/frontend
    npm run build
  working-directory: /root/steam-api/frontend

- name: Restart PM2
  run: |
    cd /root/steam-api  # Navigate to the root directory where your PM2 config file is
    pm2 restart all
  working-directory: /root/steam-api

- name: Deploy to VPS
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USERNAME }}
    key: ${{ secrets.VPS_SSH_KEY }}
    port: 22
    source: "."  # Source directory to deploy from (assuming it's the same as your working directory)
    target: "/root/steam-api"  # Target directory on your VPS
